services:
  mysql:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: swift_codes
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  
  mysql_test:
    container_name: db_test
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_swift_codes
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
