services:
  mysql:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: swift_codes
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
